FROM ubuntu:20.04

ENV TZ=Europe/Rome \
    DEBIAN_FRONTEND=noninteractive

ARG REPO_WS=/MARIO
RUN mkdir -p $REPO_WS/src
WORKDIR /home/user/$REPO_WS

RUN apt-get update

RUN apt install -y git
RUN mkdir ~/opencv_build && cd ~/opencv_build && git clone https://github.com/opencv/opencv.git && git clone https://github.com/opencv/opencv_contrib.git

RUN cd ~/opencv_build/opencv && mkdir -p build && cd build
RUN apt install -y build-essential cmake git pkg-config libgtk-3-dev libavcodec-dev libavformat-dev libswscale-dev libv4l-dev libxvidcore-dev libx264-dev libjpeg-dev libpng-dev libtiff-dev gfortran openexr libatlas-base-dev python3-dev python3-numpy libtbb2 libtbb-dev libdc1394-22-dev libopenexr-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev

RUN cd ~/opencv_build/opencv && \
    mkdir -p build && \
    cd build && \
    cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D    OPENCV_GENERATE_PKGCONFIG=ON        - D OPENCV_EXTRA_MODULES_PATH=~/opencv_build/opencv_contrib/modules -D BUILD_EXAMPLES=ON .. && \
    make -j16 && \
    make install


RUN apt-get install -y python3.8 


RUN apt install python3-pip -y
RUN apt-get install -y python3-tk  
RUN pip install pip --upgrade 

RUN pip install opencv-python==4.6.0.66  requests==2.28.0  torch==1.11.0 torchaudio==0.11.0 torchvision==0.12.0  pyyaml==6.0  tqdm==4.64.0  matplotlib==3.5.2  seaborn==0.11.2  gdown==4.4.0  cython==0.29.30  tensorboard==2.9.  easydict==1.9  scikit-learn==1.1.1  protobuf==3.20.0  Pillow==9.2.0    python-math  statistics  ezprogress numpy
RUN pip install https://github.com/KaiyangZhou/deep-person-reid/archive/master.zip
COPY . /home/user/MARIO/src

RUN cd /home/user/MARIO/src/imbs-mt && rm -r build && mkdir build && cd build && cmake .. && make
